# Generated by Django 4.2.4 on 2023-08-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=50, null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('number', models.CharField(max_length=13, null=True)),
                ('concern', models.TextField(max_length=5000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
