# Generated by Django 4.2.4 on 2023-08-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('thead0', models.CharField(default='', max_length=100)),
                ('chead0', models.TextField(default='', max_length=5000)),
                ('thead1', models.CharField(default='', max_length=100)),
                ('chead1', models.TextField(default='', max_length=5000)),
                ('thead2', models.CharField(default='', max_length=100)),
                ('chead2', models.TextField(default='', max_length=5000)),
                ('image', models.ImageField(null=True, upload_to='home/images')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('pub_by', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
    ]
